# FUNDING.yml

#GitHub Sponsors
github: ["hashemix"]
# OpenCollective
# open_collective: "opencollective-project"

# Patreon
# patreon: "patreon-username"

# Buy Me a Coffee
# buy_me_a_coffee: "bmac-username"

# Ko-fi
# ko_fi: "kofi-username"

# Custom donation links
# custom: ["https://custom-donation-link.com"]
