[version_2024_11_05]
no-default-features = true
features = "2024_11_05 schema_utils"
# release = true

[version_2025_03_26]
no-default-features = true
features = "2025_03_26 schema_utils"
# release = true

[report]
output-dir = "./.coverage"
out = ["Html", "Xml"]
