name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ascending: true
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. It will close in 7 days unless additional input is provided. If you believe this issue is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)"
          stale-pr-message: "This PR is stale because it has been open 90 days with no activity. It will close in 15 days unless additional input is provided. (This is an automated message)"
          close-issue-message: "This issue was closed because it has been stalled for 37 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 105 days with no activity."
          days-before-issue-stale: 30
          days-before-pr-stale: 90
          days-before-issue-close: 5
          days-before-pr-close: 15
          remove-pr-stale-when-updated: true
          remove-issue-stale-when-updated: true
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "roadmap,security"
          exempt-pr-labels: "work-in-progress,wip"
          operations-per-run: 300
